### PR TITLE
Modifications to allow bmat to execute robustly.  Also includes VERBOSE

### PR DESCRIPTION
**Pull request by entriken**
This update is to avoid crashes in bmat when it is passed blocks of matrices with a row or column being of zero dimension.  It also includes print statements to debug opting, governed by a VERBOSE variable.

There may be a more efficient way to write the bmat fixes.

I created a local branch called 'bob' and pushed it, but a new branch was not created on the remote site.  It seems to be pushing to the master.  Still need to work this out.

### CODE REVIEW

**Comment by ttinoco** [comment]
The suggested modifications in the bmat statements are needed, but there are lots of "verbose" and print statements left in the code. I think these should be removed once an issue has been solved.

**Comment by entriken** [comment]
Dear Tomas,

The prints are useful to me for continued development and debugging.  I can regulate them by setting the VERBOSE value.  Perhaps we can have an intermediate branch to keep the VERBOSE printing feature for learning and debugging?

Best regards,

Bob

Technical Executive
Electric Power Research Institute
3420 Hillview Avenue | Palo Alto, CA 94304
Tel: 650/855-2198 | Cell: 650/353-8956 | Fax: 650/855-2002
Email: rentrike@epri.com<mailto:rentrike@epri.com>

www.epri.com
Together...Shaping the Future of Electricity
________________________________

**Comment by ttinoco** [comment]
Please see my suggestions on the PFNET pull-request.

**Comment by ttinoco** [comment]
Closing pull request. I will generally not merge "in progress" code with debugging print statements. Also, pull requests should be done from now on to the dev branch.

**Pull request closed without merging**
